version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      WDS_SOCKET_PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
  frontend:
    build: ./frontend
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
